apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dd-agent
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dd-agent
      name: dd-agent
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: dd-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog
                key: api-key
          - name: KUBERNETES
            value: "yes"
          - name: SD_BACKEND
            value: docker
          - name: KUBERNETES_LEADER_CANDIDATE
            value: "true"
          - name: KUBERNETES_LEADER_LEASE_DURATION
            value: "300"
          #following 3 are for process metric collection
          - name: DD_PROCESS_AGENT_ENABLED
            value: "true"
          - name: HOST_PROC
            value: /host/proc
          - name: HOST_SYS
            value: /host/sys
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: dd-agent-config-volume
            mountPath: /conf.d
          #following is for process metric collection
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - name: dd-agent-config-volume
          configMap:
            name: dd-agent-config
            items:
            - key: docker-daemon.yaml
              path: docker_daemon.yaml
        #following is for process metric collection
        - hostPath:
            path: /etc/passwd
          name: passwd
