apiVersion: v1
kind: Service
metadata:
  name: node-marantz
  labels:
    app: node-marantz
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: node-marantz
